name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_VERSION: 1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        run: |
          make init
      - name: Check types with Mypy
        run: |
          make check-types
      - name: Lint with flake8
        run: |
          make lint
      - name: Run unit tests
        run: |
          make tests
